# 向量 Vector or 矩阵 Matrix

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
# a 这种 1 维的array 叫做 Vector 向量

In [3]:
b = np.array(a).reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
b.ndim

2

In [5]:
# b 这种 二维 的array 叫做 矩阵 Matrix 
# 运用的时候回一维和多维混合运用

In [7]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [12]:
a = np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [ ]:
#  两个有相同的参数叫做step ,每一个相差的步数


In [13]:
a = np.arange(0,11,2)
a

array([ 0,  2,  4,  6,  8, 10])

In [22]:
b = np.linspace(0,11,11) #固定的范围
b

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

In [15]:
# arange 是n -1 的值, linspace 是n 

In [16]:
type(1)

int

In [17]:
type(1.2)

float

In [23]:
# 0.0 = 0 , 1.0  都是float

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Np Random 随机数

In [31]:
import numpy as np

In [32]:
np.random.rand()
#uniform distribution 我们生成的数是0到1 之间的每一个数
#所有的数生成的几率都是一样的,没有哪一个比较多,哪一个比较少

0.3852474594828156

In [33]:
np.random.rand(1)

array([0.58358018])

In [34]:
np.random.rand(2)

array([0.45196   , 0.20157663])

In [36]:
np.random.rand(5,4)
# rand ( ()) 里面的参数不能是tuple, 只能是int

array([[0.3454014 , 0.87123947, 0.90479094, 0.86739574],
       [0.97345906, 0.59583132, 0.39226359, 0.26592137],
       [0.78633302, 0.9819631 , 0.11962054, 0.12019949],
       [0.11814302, 0.00791379, 0.20708321, 0.05331539],
       [0.26138602, 0.10792171, 0.44839568, 0.02997722]])

In [39]:
np.random.randn(5,4)
#0 作为无限大 跟无限小的中间的值,越接近0 生成的几率越大
#  不是随机分配,越靠近0中心的随机数的几率会多一些

array([[-0.66041532, -0.32215717, -1.67663621,  0.50233697],
       [ 0.27506977,  0.72521245, -1.12936614,  1.09650725],
       [-1.05341752, -1.04299685, -0.25303577, -1.13136518],
       [ 1.27441351,  0.71573309,  1.09796717,  1.91579835],
       [ 0.22078155, -2.12171236,  2.14782918,  1.11721152]])

In [42]:
np.random.randint(1,100)

61

In [43]:
np.random.randint(1,100,10)

array([30, 70, 84,  5, 52, 67, 80, 74, 77, 27])

In [44]:
np.random.randint(1,100,(6,5))

array([[46, 97, 77, 52, 33],
       [ 5, 47, 49, 31, 90],
       [42, 24, 74, 97, 19],
       [83, 34,  4,  2, 14],
       [56, 89, 81, 82,  2],
       [23, 83, 42, 41, 80]])

In [47]:
np.random.randint(1,100,25).reshape(5,5)

array([[14, 51, 68, 13,  6],
       [34, 68, 41, 77,  4],
       [42, 39, 89, 78, 52],
       [81, 56, 37, 51, 56],
       [66, 44,  5, 47, 14]])

In [48]:
np.random.randint(1,100,25).reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [49]:
# 由于我们5 乘以 4 还有5 个对象没有, 无法生成5 乘以 5 
# 后面shape 相乘结果必须是我们生成的个数

In [53]:
np.random.randint(1,100,25).reshape(25,1)

array([[32],
       [36],
       [ 7],
       [44],
       [85],
       [95],
       [36],
       [50],
       [53],
       [90],
       [98],
       [ 8],
       [84],
       [25],
       [43],
       [26],
       [28],
       [47],
       [59],
       [18],
       [48],
       [53],
       [13],
       [46],
       [63]])

In [54]:
randarr = np.random.randint(1,100,25).reshape(5,5)
randarr

array([[94,  4, 96, 87, 89],
       [35, 46, 65,  4, 34],
       [58, 67, 57, 64, 20],
       [68, 63, 33, 24, 15],
       [94, 34, 22, 42, 94]])

In [55]:
randarr.max()

96

In [56]:
randarr.argmax() # 最大的所在index 位置

2

In [57]:
randarr.min()

4

In [59]:
randarr.argmin() # 最小的所在index 位置

1

# Array Indexing & slicing

In [61]:
import numpy as np

In [62]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
a[6] # index

6

In [64]:
a[2:6] # slicing

array([2, 3, 4, 5])

In [65]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [66]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
# 这一部分array 读取slicing 和list 一样的

## slicing Matrix 

In [68]:
a = np.random.randint(1,50,(3,3))
a

array([[30, 18,  3],
       [ 2, 47, 38],
       [22, 48,  2]])

In [69]:
a[0]

array([30, 18,  3])

In [70]:
a[1]

array([ 2, 47, 38])

In [72]:
a[2]  # first index is for row

array([22, 48,  2])

In [73]:
a[1][2]

38

In [74]:
a[1,2]

38

In [75]:
a

array([[30, 18,  3],
       [ 2, 47, 38],
       [22, 48,  2]])

In [76]:
a[2,1]

48

In [77]:
# 以上是matrix 的index

In [78]:
# 一下开始matrix 的slicing 

In [79]:
a

array([[30, 18,  3],
       [ 2, 47, 38],
       [22, 48,  2]])

In [80]:
a[:2,1:]

array([[18,  3],
       [47, 38]])

In [81]:
a[1:,:2]

array([[ 2, 47],
       [22, 48]])

In [82]:
a = np.random.randint(1,50,20)
a

array([15, 33, 29, 40, 49,  1, 34, 17,  9, 44, 41, 49, 47, 36, 17,  4, 11,
        1, 33, 22])

In [83]:
# 我们希望筛选值

In [84]:
a > 20

array([False,  True,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True,  True])

In [85]:
newarray = a[a>20]
newarray

array([33, 29, 40, 49, 34, 44, 41, 49, 47, 36, 33, 22])