In [29]:
# NumPy 是什么
# google www.numpy.org
# 多维度数据,大数据
# 相同硬件情况下, Numpy 运算时17分之一 更快!
# 除了速度加快,而且不需要循环,循环时间比较长

In [2]:
g = list(range(1000000))

In [4]:
%timeit sum(g)   # 运算一下平均运算时长

23.2 ms ± 484 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
import numpy as np

In [6]:
g_array = np.array(g) # numpy 不用list 用array

In [9]:
%timeit np.sum(g_array) # 1ms 毫秒 = 1000 us 微秒

451 µs ± 44.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
a = [1,2,3,4]

In [11]:
b = [10,11,12,13]

In [12]:
a + b

[1, 2, 3, 4, 10, 11, 12, 13]

In [18]:
#这样做他只会append 到回来,不会两个list 相加

In [14]:
zip(a,b)   # transfer zip 

In [15]:
output = []

In [16]:
for item1, item2 in zip(a,b):
    output.append(item1 + item2)
    

In [17]:
output

[11, 13, 15, 17]

In [19]:
# 这样可以得到
# 但是numpy 不会那么麻烦

In [20]:
a = np.array([1,2,3,4])

In [21]:
b = np.array([10,11,12,13])

In [22]:
a

array([1, 2, 3, 4])

In [23]:
b

array([10, 11, 12, 13])

In [24]:
a + b

array([11, 13, 15, 17])

In [25]:
a * b

array([10, 22, 36, 52])

In [26]:
a / b

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [28]:
a ** b # a 的 b 次 幂

array([       1,     2048,   531441, 67108864], dtype=int32)

# Numpy Array

In [30]:
# 当数据几百万, list 就不好用, array 就会很好的处理

In [31]:
import numpy as np

In [32]:
mylist = [1,2,3]

In [33]:
mylist

[1, 2, 3]

In [34]:
np.array(mylist)

array([1, 2, 3])

In [36]:
myarray = np.array([1,2,3])
myarray

array([1, 2, 3])

In [38]:
mylist = [1,2.0,"abc", True]
mylist

[1, 2.0, 'abc', True]

In [39]:
np.array(mylist)

array(['1', '2.0', 'abc', 'True'], dtype='<U32')

In [40]:
# 在np array ,每一个array 只允许一种类型的数据,可以忽略所有原数据类型的转换

In [44]:
a = np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [45]:
type(a)

numpy.ndarray

In [46]:
#nd指的是 array 这个宿主 可以是multi dimension 多个维度

In [47]:
a.ndim # 可以看他有多少维度

1

In [48]:
a.shape # 他的形状

(6,)

In [51]:
a = a.reshape((2,3)) # 改成 2 个row , 3 个column
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a.ndim

2

In [53]:
# 表示reshape 之后 维度从1 变成2 

In [54]:
a.shape

(2, 3)

In [55]:
# 初学 宿主 array 最容易混淆的是如何看他的维度 其实他跟row 没有关系的

In [56]:
a = a.reshape((1,6)) 
a

array([[1, 2, 3, 4, 5, 6]])

In [57]:
a.ndim

2

In [58]:
#这时候他在1 row ,但是他的dimension 还是在 2 
#他的row 跟 维度是没有关系的
#跟他的层次有关系
# 第一个[]把他包裹一起算一层, 这里有两个[ [] ] 所以是2 dimension

In [59]:
a = a.reshape((2,3)) # 改成 2 个row , 3 个column
a

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a.ndim

2

In [62]:
# 虽然这里有3 对[], 但是中间两对[]是在同一个层次, 所以算作1 dimension
# , 逗号 表示的是并列的关系

In [63]:
a = np.array([1,2,3,4,5,6])

In [64]:
a.ndim

1

In [65]:
a = np.array([[1,2,3,4,5,6]])

In [66]:
a.ndim

2

In [67]:
a.shape

(1, 6)

In [68]:
a = np.array([[[1,2,3,4,5,6]]])

In [69]:
a.ndim

3

In [70]:
a.shape

(1, 1, 6)

In [71]:
#  这个tuple里面有多少个成员我们的dimension 就有多少个

# Numpy Array 特性

In [73]:
import numpy as np

In [75]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [76]:
a[0] = 10
a

array([10,  1,  2,  3])

In [77]:
a.dtype

dtype('int32')

In [79]:
a[0] = 10.8
a

array([10,  1,  2,  3])

In [80]:
#这里赋值10.8 不成功,因为当我们考虑赋值的时候我们首先会考虑他的type
# 这里是int, 这里赋予float 他会自动转化为int,添加进去,他对类型非常在乎
# 这个类型是一开始我们定义来定义

In [81]:
a = np.array([1,2,3,4])
a.dtype

dtype('int32')

In [82]:
a = np.array([1,2,3,4.0])
a.dtype

dtype('float64')

In [84]:
# 我们也可以预设给他dtype
a = np.array([1,2,3,4.0],dtype="int32")
a.dtype

dtype('int32')

In [85]:
c = np.array([[10,11,12],[20,21,22]])
c

array([[10, 11, 12],
       [20, 21, 22]])

In [86]:
c.ndim

2

In [87]:
c.shape

(2, 3)

In [88]:
#(Row,Column) shape 会显示他有几row,几column 他是C语言的进阶