In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(6,4) # 6 dataset 4 sample data
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a.mean() # mean for everyone

11.5

In [5]:
a.mean(axis = 0) # .reshape(6,4) 6 row位置消失 得到 4 个column 位置

array([10., 11., 12., 13.])

In [6]:
a.mean(axis = 0).shape

(4,)

In [8]:
# (2,3) axis = 0 # (3,) 2 代表0 维度消失 
# (2,5,2,7,2,4) axis = 3 # (2,5,2,2,4) 7代表3 维度会消失
# (3,4,5) axis = -1 # (3,4) 5 代表-1 维度消失

In [10]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a.mean(axis = -1) #

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [14]:
a.mean(axis = 1) # reshape(6,4) 4 column 位置消失 得到6 个row 的元素

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [16]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
b.sum(axis=0) # reshape(2,3)  -- 2 位置消失,得到 3 个元素

array([3, 5, 7])

In [20]:
b.sum(axis=0).shape

(3,)

In [23]:
c = np.arange(60).reshape(3,4,5) #加维度在第一个3 个, 4 个row 5 个column
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [24]:
c.sum(axis=1).shape # (3,4,5) 把4 弄掉 降低一个维度

(3, 5)

In [26]:
c.sum(axis=1) # (3,5) -- 3 row , 5 column

array([[ 30,  34,  38,  42,  46],
       [110, 114, 118, 122, 126],
       [190, 194, 198, 202, 206]])

# opencv-python 

In [29]:
# https://pypi.org/
# opencv-python install 

In [30]:
#numpy处理图片

In [1]:
import numpy as np
import cv2

In [2]:
# 这里有3 个list 维度
#每一个list 有三个成员 代表图片里面的每一个点
#每一个点都是颜色通道 red,green,blue 
#每一个颜色通道值都是0-225直接

In [3]:
image = cv2.imread("myphoto.jpg") 

In [4]:
point = image[50,500]  # 像素 50 row , 500 column 

In [5]:
point = [255,255,255] # 把这个点变成白色

In [7]:
image[100:150, 500:550] = [255,255,255]

In [ ]:
plant = image[90:340, 80:403] # 第一个Y 纵向90 到340, 第二个X 横向

In [6]:
image[90:340,800-(403 - 80):800] = plant

In [8]:
print(point)

[255, 255, 255]


In [9]:
#找一个点不容易,图片很大

In [7]:
cv2.imshow("input_image", image)
cv2.waitKey(0) #等待, 0 是无限等待直到用户输入某一个key 才继续
cv2.destroyAllWindows()

In [ ]:
# 大神级别的获取image 坐标
import numpy as np
import cv2

img = cv2.imread("cat.jpg")

def on_EVENT_LBUTTONDOWN(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        xy = "%d,%d" % (x, y)
        print(x,y)
        cv2.circle(img, (x, y), 1, (255, 0, 0), thickness = -1)
        cv2.putText(img, xy, (x, y), cv2.FONT_HERSHEY_PLAIN,
                    1.0, (0,0,0), thickness = 1)
        cv2.imshow("image", img)

cv2.namedWindow("image")
cv2.setMouseCallback("image", on_EVENT_LBUTTONDOWN)
cv2.imshow("image", img)

while(True):
    try:
        cv2.waitKey(100)
    except Exception:
        cv2.destroyWindow("image")
        break
        
cv2.waitKey(0)
cv2.destroyAllWindows()

518 48
496 545
515 272
795 287
325 53


In [ ]:
# 移花接木

In [9]:
import numpy as np
import cv2
image = cv2.imread("myphoto.jpg") 
plant = image[90:340, 80:403]
image[90:340,800-(403 - 80):800] = plant
cv2.imshow("input_image", image)
cv2.waitKey(0) 
cv2.destroyAllWindows()


# 躲猫猫

In [16]:
import numpy as np
import cv2
image = cv2.imread("cat.jpg") 
cat = image[48:540, 515:795]
image[48:540,515-280:795-280] = cat
image[48:540, 515:795] = [255,255,255]
#image[90:340,800-(403 - 80):800] = plant
cv2.imshow("input_image", image)
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [17]:
import numpy as np
import cv2
image = cv2.imread("cat.jpg") 
cat = image[48:540, 515:795]
image[48:540,515-280:795-280] = cat
image[48:540, 515:795] = [255,255,255]
cv2.imshow("input_image", image)
cv2.waitKey(0) 
cv2.destroyAllWindows()


In [18]:
import numpy as np
import cv2
image = cv2.imread("cat.jpg") 
cat = image[48:540, 515:795]
image[48:540,515-380:795-380] = cat
image[48:540, 515:795] = [255,255,255]
cv2.imshow("input_image", image)
cv2.waitKey(0) 
cv2.destroyAllWindows()


In [19]:
import numpy as np
import cv2
image = cv2.imread("cat.jpg") 
# cat = image[48:540, 515:795]
# image[48:540,515-280:795-280] = cat
# image[48:540, 515:795] = [255,255,255]
cv2.imshow("input_image", image)
cv2.waitKey(0) 
cv2.destroyAllWindows()

---

In [5]:
import numpy as np
import cv2
image = cv2.imread("cat.jpg") 

count = 0
while True:
    
    if count > 1:
        break
    else:
        # 1 cat
        cv2.imshow("input_image", image)
        cv2.waitKey(1500) 
        cv2.destroyAllWindows()

        # 2 cat
        cat = image[48:540, 515:795]
        image[48:540,515-280:795-280] = cat
        image[48:540, 515:795] = [255,255,255]
        cv2.imshow("input_image", image)
        cv2.waitKey(1500) 
        cv2.destroyAllWindows()

        # 3 cat
        cat = image[48:540,515-280:795-280]
        image[48:540,515-480:795-480] = cat
        image[48:540,515-210:795-280] = [255,255,255]
        cv2.imshow("input_image", image)
        cv2.waitKey(1500) 
        cv2.destroyAllWindows()

        #4 cat
        image = cv2.imread("cat.jpg") 
        cv2.imshow("input_image", image)
        cv2.waitKey(1500) 
        cv2.destroyAllWindows()
        count += 1